// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          int64            `json:"id"`
	Code        string           `json:"code"`
	OriginalUrl string           `json:"original_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
