// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CheckCodeExists(ctx context.Context, code string) (int32, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	GetURLByCode(ctx context.Context, code string) (Url, error)
}

var _ Querier = (*Queries)(nil)
